### ISSUE TITLE
Feature request - Export to ePub

### ISSUE THREAD

**Issue by Myddna** [amontane/morti#1]
Hi!

I'm in the beta and I wanted to make a suggestion ;)

Would it be possible to export the book to ePub format? As far as I know is an open format based on XML, and looks really good on e-readers.

**Comment by amontane** [comment]
Hey! :D 

It would be possible, indeed. When I have some I'll make some research and see if I can manage it. Meanwhile, it'll have to be pdf. I tested it on 5, 6 and 7 inch devices and it looked acceptable. Did you have troubles with some concrete device?

**Comment by Myddna** [comment]
Not really, but the lines look too close one another to be comfortable to read ;P
