### ISSUE TITLE
Comment

### ISSUE THREAD

**Issue by Myddna** [amontane/morti#3]
In cannot post this comment: 

> balda3.
> (Del cat. balda, y este del ár. hisp. aḍḍábba 'pestillo').
> 1. f. Ar. aldaba (‖ barreta para atrancar las puertas).
> 
> Aldaba es más común en castellano que balda

What's wrong? :__(

I cannot pos this either:

> balda3.(Del cat. balda, y este del ár. hisp. aḍḍábba 'pestillo'). 1. f. Ar. aldaba (barreta para atrancar las puertas). (Aldaba es más común en castellano que balda)

**Comment by amontane** [comment]
This looks like a crazy bug!!! I'd bet the single quotes are responsible, even if I'm escaping them. I'm probably messing up big time. Thanks for reporting! :D

EDIT: Omg, this is a jumbo vulnerability: I was not escaping the comment field. I put a quick hotfix to the server, I'm going to fix the issue in the code asap. Thanks for reporting before Little Bobby Tables made his appearance! ^^u

**Comment by Myddna** [comment]
:D
